/* COSC 4800 ASSIGNMENT 6
 * Autogenerated constructor and setters/getters
 * @AUTHOR CLARE FITZGERALD
 * DATE: 12/6/2023
 * INSTRUCTOR 4800 DR. MADIRAJU
 * 
 */
package com.domain;

public class Paper {
	private String paperid;
	private String title;
	private String filename;
	private String contactauthoremail;
	private String Abstract;
	public Paper(String paperid, String title, String filename, String contactauthoremail, String abstract1) {
		super();
		this.paperid = paperid;
		this.title = title;
		this.filename = filename;
		this.contactauthoremail = contactauthoremail;
		this.Abstract = abstract1;
	}
	
	public Paper(String paperid, String title) {
		super();
		this.paperid = paperid;
		this.title = title;
	}

	public String getPaperid() {
		return paperid;
	}
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getFilename() {
		return filename;
	}
	public void setFilename(String filename) {
		this.filename = filename;
	}
	public String getContactauthoremail() {
		return contactauthoremail;
	}
	public void setContactauthoremail(String contactauthoremail) {
		this.contactauthoremail = contactauthoremail;
	}
	public String getAbstract() {
		return Abstract;
	}
	public void setAbstract(String abstract1) {
		Abstract = abstract1;
	}

	@Override
	public String toString() {
		return "Paper [paperid=" + paperid + ", title=" + title + ", filename=" + filename + ", contactauthoremail="
				+ contactauthoremail + ", Abstract=" + Abstract + "]";
	}
	
	


}

