/* COSC 4800 ASSIGNMENT 6
 * Autogenerated constructor and setters/getters
 * @AUTHOR CLARE FITZGERALD
 * DATE: 12/6/2023
 * INSTRUCTOR 4800 DR. MADIRAJU
 * 
 */
package com.domain;


public class Participator {
	private String fname;
	private String lname;
	private String minit;
	private String email;
	private String phone;
	private String affiliation;

	

	public Participator(String email, String fname, String minit, String lname,   String phone, String affiliation) {
		super();
		this.fname = fname;
		this.lname = lname;
		this.minit = minit;
		this.email = email;
		this.phone = phone;
		this.affiliation = affiliation;
	}



	public String getFname() {
		return fname;
	}



	public void setFname(String fname) {
		this.fname = fname;
	}



	public String getLname() {
		return lname;
	}



	public void setLname(String lname) {
		this.lname = lname;
	}



	public String getMinit() {
		return minit;
	}



	public void setMinit(String minit) {
		this.minit = minit;
	}



	public String getEmail() {
		return email;
	}



	public void setEmail(String email) {
		this.email = email;
	}



	public String getPhone() {
		return phone;
	}



	public void setPhone(String phone) {
		this.phone = phone;
	}



	public String getAffiliation() {
		return affiliation;
	}



	public void setAffiliation(String affiliation) {
		this.affiliation = affiliation;
	}



	@Override
	public String toString() {
		return "Participator [fname=" + fname + ", lname=" + lname + ", minit=" + minit + ", email=" + email
				+ ", phone=" + phone + ", affiliation=" + affiliation + "]";
	} 

}
